
class vehicles_3as : vehicles_base
{
    // APCs and Transport Vehicles
    ITEM(3AS_Jug_Imperial, 15500, "APC", VEHICLE_CONDITION_APC);
    ITEM(3AS_ITT, 14000, "APC", VEHICLE_CONDITION_APC);
    ITEM(3AS_PX10_IMP_F, 18000, "APC", VEHICLE_CONDITION_APC);
    ITEM(3AS_PX10_IMP_R3, 19500, "APC", VEHICLE_CONDITION_APC);
    ITEM(3AS_PX10_IMP_UP, 20000, "APC", VEHICLE_CONDITION_APC);
    ITEM(3AS_AV7, 17500, "APC", VEHICLE_CONDITION_APC);
    ITEM(3AS_Imperial_Transport_01, 22000, "APC", VEHICLE_CONDITION_APC);
    // Artillery
    ITEM(3as_XX9, 38000, "ARTILLERY", VEHICLE_CONDITION_ARTILLERY);
    
    ITEM(3AS_LAAT_Mk1_Imperial, 45000, "HELI", VEHICLE_CONDITION_HELI);
    ITEM(3AS_LAAT_Mk1Lights_Imperial, 47000, "HELI", VEHICLE_CONDITION_HELI);
    ITEM(3AS_Patrol_LAAT_Imperial, 42000, "HELI", VEHICLE_CONDITION_HELI);

    ITEM(3AS_Gozanti_F, 25000, "PLANE", VEHICLE_CONDITION_PLANE);
    ITEM(3AS_SandSpeeder, 6500, "PLANE", VEHICLE_CONDITION_PLANE);
    ITEM(3AS_Rho_IMP_F, 48500, "PLANE", VEHICLE_CONDITION_PLANE);
    ITEM(3AS_Z95_Republic, 35000, "PLANE", VEHICLE_CONDITION_PLANE);
    ITEM(3as_V19_base, 32000, "PLANE", VEHICLE_CONDITION_PLANE);
    ITEM(3AS_Delta7_F, 38000, "PLANE", VEHICLE_CONDITION_PLANE);
    ITEM(3AS_Delta7_ANI, 40000, "PLANE", VEHICLE_CONDITION_PLANE);
    ITEM(3AS_Delta7_PLO, 39000, "PLANE", VEHICLE_CONDITION_PLANE);
    ITEM(3AS_Delta7_TANO, 39500, "PLANE", VEHICLE_CONDITION_PLANE);
    ITEM(3AS_BTLB_Bomber, 52000, "PLANE", VEHICLE_CONDITION_PLANE);
    ITEM(3AS_ARC_170_Blue, 46000, "PLANE", VEHICLE_CONDITION_PLANE);
    ITEM(3AS_N99, 34000, "PLANE", VEHICLE_CONDITION_PLANE);
    ITEM(3AS_VWing_Imperial, 41000, "PLANE", VEHICLE_CONDITION_PLANE);
    
    // Static Anti-Air
	ITEM(3AS_Keeradak_Imperial, 4200, "STATICAA", VEHICLE_CONDITION_STATICAA);
    ITEM(3as_FlakCannon, 4200, "STATICAA", VEHICLE_CONDITION_STATICAA);
    // Static Anti-Tank
    ITEM(3AS_StationaryTurret, 5800, "STATICAT", VEHICLE_CONDITION_STATICAT);
    ITEM(3as_ParticleCannon, 45000, "STATICAT", VEHICLE_CONDITION_STATICAT);
    ITEM(3AS_J1_Proton_Legged, 62000, "STATICAT", VEHICLE_CONDITION_STATICAT);
    
    // Static Machine Guns
    ITEM(3AS_HeavyRepeater_Unarmoured, 3500, "STATICMG", VEHICLE_CONDITION_STATICMG);
    ITEM(3AS_HeavyRepeater_Armoured, 3900, "STATICMG", VEHICLE_CONDITION_STATICMG);
    ITEM(3AS_J10s_F, 58000, "STATICMG", VEHICLE_CONDITION_STATICMG);
    // Tanks and Heavy Vehicles
    ITEM(3AS_RX200_Base, 16000, "AA", VEHICLE_CONDITION_AA);
    ITEM(3AS_ATAP_Base, 12000, "TANK", VEHICLE_CONDITION_TANK);
    ITEM(3AS_ATAT, 75000, "TANK", VEHICLE_CONDITION_TANK);
    ITEM(3AS_ATAT_Command, 85000, "TANK", VEHICLE_CONDITION_TANK);
    ITEM(3AS_ATAT_Elite, 95000, "TANK", VEHICLE_CONDITION_TANK);
    ITEM(3AS_ATTE_Imperial, 68000, "TANK", VEHICLE_CONDITION_TANK);
    ITEM(3AS_Heavy_AAT_Shield_F, 65000, "TANK", VEHICLE_CONDITION_TANK);
    ITEM(3AS_Heavy_AAT_Flamer_F, 63000, "TANK", VEHICLE_CONDITION_TANK);
    ITEM(3AS_AAT_tan, 55000, "TANK", VEHICLE_CONDITION_TANK);
};

