class mod_unlimited_base : forbidden_unlimited_base 
{
    addons[] = {"Required CfgPatches entry(s)"};
};

class mod_limited_base : forbidden_limited_base 
{
    addons[] = {"LF_Weapon_Unit_Melee", "WBK_Lightsabers"};
};

// Can be weapon, magazine, vest, etc. Basically anything that can either go in the arsenal or a crate

class Equipment_Classname : mod_unlimited_base {}; // Will not appear in crates, but can be unlimited in the arsenal

class Equipment_Classname_2 : mod_limited_base {"LFP_Lightsaber_Ault_b", 
"LFP_Lightsaber_Ault_c", 
"LFP_Lightsaber_Ault_g",
"LFP_Lightsaber_Ault_i", 
"LFP_Lightsaber_Ault_o", 
"LFP_Lightsaber_Ault_p", 
"LFP_Lightsaber_Ault_r", 
"LFP_Lightsaber_Ault_w", 
"LFP_Lightsaber_Ault_y",
"Buba_saber",
"LFP_Candy_Blue_LightSaber",
"LFP_Candy_Green_LightSaber",
"LFP_Candy_Pink_LightSaber",
"LFP_Candy_Purple_LightSaber",
"LFP_Candy_Red_LightSaber",
"LFP_Candy_White_LightSaber",
"LFP_Candy_Orange_LightSaber",
"LFP_Lightsaber_Crossguard_b",
"LFP_Lightsaber_Crossguard_g",
"LFP_Lightsaber_Crossguard_i",
"LFP_Lightsaber_Crossguard_o",
"LFP_Lightsaber_Crossguard_p",
"LFP_Lightsaber_Crossguard_r",
"LFP_Lightsaber_Crossguard_w",
"LFP_Lightsaber_Crossguard_y",
"LFP_DarkSaber",
"LFP_lightsaber",
"LFP_Lightsaber_Glowe_b",
"LFP_Lightsaber_Glowe_g",
"LFP_Lightsaber_Glowe_i",
"LFP_Lightsaber_Glowe_o",
"LFP_Lightsaber_Glowe_p",
"LFP_Lightsaber_Glowe_r",
"LFP_Lightsaber_Glowe_w",
"LFP_Lightsaber_Glowe_y",
"LFP_Lightsaber_Demi",
"LWT_Lightsaber_Issan",
"LST_Lightsaber_Thagoron",
"LFP_Lightsaber_K_b",
"LFP_Lightsaber_K_g",
"LFP_Lightsaber_K_i",
"LFP_Lightsaber_K_o",
"LFP_Lightsaber_K_p",
"LFP_Lightsaber_K_r",
"LFP_Lightsaber_K_w",
"LFP_Lightsaber_K_y",
"LFP_Lightsaber_Jedikatansvord_4",
"LFP_Lightsaber_Jedikatansvord_8",
"LFP_Lightsaber_Jedikatansvord_3",
"LFP_Lightsaber_Jedikatansvord_7",
"LFP_Lightsaber_Jedikatansvord_9",
"LFP_Lightsaber_Jedikatansvord_1",
"LFP_Lightsaber_Jedikatansvord_2",
"LFP_Lightsaber_Jedikatansvord_5",
"LFP_Lightsaber_Jedikatansvord_6",
"LFP_kella",
"WBK_lightsaber_jedi_TwoSided_Green",
"WBK_lightsaber_jedi_TwoSided_Blue",
"WBK_lightsaber_jedi_TwoSided_Purple",
"WBK_lightsaber_jedi_TwoSided_Yellow",
"WBK_lightsaber_jedi_TwoSided_Pink",
"WBK_lightsaber_jedi_TwoSided_White",
"LST_Lightsaber_Thagoron_Dual",
"LFP_Lightsaber_Acklay_IB",
"LFP_Lightsaber_kela_saber",
"LFP_Lightsaber_Lin_b",
"LFP_Lightsaber_Lin_g",
"LFP_Lightsaber_Lin_i",
"LFP_Lightsaber_Lin_o",
"LFP_Lightsaber_Lin_p",
"LFP_Lightsaber_Lin_r",
"LFP_Lightsaber_Lin_w",
"LFP_Lightsaber_Lin_y",
"LFP_Lightsaber_Lin_Lincord",
"LFP_linkor",
"LFP_Lightsaber_sword_dv_3",
"LFP_Lightsaber_sword_dv_7",
"LFP_Lightsaber_sword_dv_4",
"LFP_Lightsaber_sword_dv_8",
"LFP_Lightsaber_sword_dv_9",
"LFP_Lightsaber_sword_dv",
"LFP_Lightsaber_sword_dv_2",
"LFP_Lightsaber_sword_dv_5",
"LFP_Lightsaber_sword_dv_6",
"LFP_Lightsaber_Maragoshi_b",
"LFP_Lightsaber_Maragoshi_g",
"LFP_Lightsaber_Maragoshi_i",
"LFP_Lightsaber_Maragoshi_o",
"LFP_Lightsaber_Maragoshi_p",
"LFP_Lightsaber_Maragoshi_r",
"LFP_Lightsaber_Maragoshi_w",
"LFP_Lightsaber_Maragoshi_y",
"LFP_Lightsaber_Revenger_b",
"LFP_Lightsaber_Revenger_g",
"LFP_Lightsaber_Revenger_i",
"LFP_Lightsaber_Revenger_o",
"LFP_Lightsaber_Revenger_p",
"LFP_Lightsaber_Revenger_r",
"LFP_Lightsaber_Revenger_w",
"LFP_Lightsaber_Revenger_y",
"LFP_Lightsaber_Rezor_b",
"LFP_Lightsaber_Rezor_g",
"LFP_Lightsaber_Rezor_i",
"LFP_Lightsaber_Rezor_o",
"LFP_Lightsaber_Rezor_p",
"LFP_Lightsaber_Rezor_r",
"LFP_Lightsaber_Rezor_w",
"LFP_Lightsaber_Rezor_y",
"LFP_Lightsaber_Skywalker_b",
"LFP_Lightsaber_Skywalker_g",
"LFP_Lightsaber_Skywalker_i",
"LFP_Lightsaber_Skywalker_o",
"LFP_Lightsaber_Skywalker_p",
"LFP_Lightsaber_Skywalker_r",
"LFP_Lightsaber_Skywalker_w",
"LFP_Lightsaber_Skywalker_y",
"LFP_Lightsaber_Tarn_b",
"LFP_Lightsaber_Tarn_g",
"LFP_Lightsaber_Tarn_i",
"LFP_Lightsaber_Tarn_o",
"LFP_Lightsaber_Tarn_p",
"LFP_Lightsaber_Tarn_r",
"LFP_Lightsaber_Tarn_w",
"LFP_Lightsaber_Tarn_y",
"LFP_sword_zan",
"LFP_zandual"
"WBK_lightsaber4_jedi",
"WBK_lightsaber4_green",
"WBK_lightsaber4_sith",
"WBK_lightsaber4_yellow",
"WBK_lightsaber_jedi_TwoSided",
"WBK_lightsaber_sith_TwoSided",
"WBK_lightsaber3_jedi",
"WBK_lightsaber3_sith",
"WBK_lightsaber3_green",
"WBK_lightsaber3_yellow",
"WBK_lightsaber3_pink",
"WBK_lightsaber3_white",
"WBK_lightsaber3_purple",
"WBK_lightsaber2_jedi",
"WBK_lightsaber2_sith",
"WBK_lightsaber2_green",
"WBK_lightsaber2_yellow",
"WBK_lightsaber2_pink",
"WBK_lightsaber2_white",
"WBK_lightsaber2_purple",
"WBK_lightsaber1_jedi",
"WBK_lightsaber1_sith",
"WBK_lightsaber1_green",
"WBK_lightsaber1_yellow",
"WBK_lightsaber1_pink",
"WBK_lightsaber1_white",
"WBK_lightsaber1_purple",
"WBK_lightsaber_jedi",
"WBK_lightsaber_sith",
"WBK_lightsaber_green",
"WBK_lightsaber_yellow",
"WBK_lightsaber_pink",
"WBK_lightsaber_white",
"WBK_lightsaber_purple",
"WBK_lightsaberOldRep_kyloStyle",
"WBK_lightsaberOldRep_jedi"
}; // Will not appear in crates, and can't be unlimited in the arsenal


//@Last Force Project
//@Lightsabers and Force

,

